services:
  assistant:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "app.assistant.main:app", "--host", "0.0.0.0", "--port", "8003"]
    restart: unless-stopped
    environment:
      - COLLECTOR_URL=http://collector:8001
    volumes:
      - /home/extdrv/mg/:/app/data
    ports:
      - "8003:8003"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8003/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - mg_net

networks:
  mg_net:
    external: true
    name: mg_net