version: "3.8"

services:
  collector:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/extdrv/mg/:/app/data
    restart: unless-stopped

  assistant:
    build:
      context: .
      dockerfile: Dockerfile
    #container_name: mg-assistant
    env_file:
      - .env
    command: ["uvicorn", "app.assistant.main:app", "--host", "0.0.0.0", "--port", "8003"]

    volumes:
      - /home/extdrv/mg/:/app/data
    restart: unless-stopped

volumes:
  data: